# Generated by Django 4.1 on 2022-08-08 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_alter_recipe_user"),
        ("ingredients", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="recipes",
            field=models.ManyToManyField(
                related_name="ingredientsss", to="recipes.recipe"
            ),
        ),
    ]
